### ISSUE TITLE
Provided example doens't work

### ISSUE THREAD

**Issue by bonedaddy** [rffrancon/ipsl#1]
Command ran: 
```
solidity@darkmatter:~$ ipsl links add --ipfs QmZJJZ4pEa88wqvgVDjTVHy89ZKbNnemg4GecKAHgZZB7E --https www.ebi.ac.uk/ena/data/view/A00145%26display%3Dfasta
```
```Error: invalid 'ipfs ref' path
Traceback (most recent call last):
  File "/home/solidity/.local/bin/ipsl", line 9, in <module>
    load_entry_point('ipsl==0.1', 'console_scripts', 'ipsl')()
  File "/home/solidity/.local/lib/python3.5/site-packages/ipsl/ipsl.py", line 56, in run
    command.run(args)
  File "/home/solidity/.local/lib/python3.5/site-packages/ipsl/cmd/links.py", line 139, in run
    command(**args)
  File "/home/solidity/.local/lib/python3.5/site-packages/ipsl/cmd/links.py", line 120, in add
    _map = maps.get()
  File "/home/solidity/.local/lib/python3.5/site-packages/ipsl/cmd/maps.py", line 114, in get
    _map = ipfs_api.dag_get(map_cid)
  File "/home/solidity/.local/lib/python3.5/site-packages/ipsl/common/ipfs.py", line 55, in _dag_get
    stdout = subprocess.check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ipfs', 'dag', 'get', 'zdpuAxvfCoKh1r1P4cqsinCdgnsSFCqjLhiLq4HaurxDs8M7V\n']' returned non-zero exit status 1
```

**Comment by ffranr** [comment]
Thanks for raising this issue.

This bug does not occur with go-ipfs v0.4.11 but does occur with v0.4.15. In v0.4.15 a trailing newline character was added to the stdout of the `dag put` command. The IPFS python API does not currently support the `dag` command. I've implemented my own interface.

This commit has been merged into master and should fix the problem: a36a6c3a52e3452699622e93db67ef0326068000

If you have time, please let me know if it's worked. Will keep the issue open for a few days.

**Comment by ffranr** [comment]
You'll probably need to run `ipfs files rm /ipsl/config.json` to remove your corrupted IPSL configuration file.

**Comment by bonedaddy** [comment]
alright let me try that now. It works, thank you :)
